# azure-pipelines-ci.yml
#
# Copyright (c) 2020 Radu Traian Jipa
# License: https://opensource.org/licenses/MIT
#
# Continuous integration pipeline for the project.


trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - '*'

variables:
  sourceBranch: 'initial'
  targetBranch: 'default'


stages:
- stage: First
  jobs:
  - job: First
    steps:
    - bash: |
        echo "Hello, World!"
        echo sourceBranch: $(Build.SourceBranch)
        echo targetBranch: $(System.PullRequest.TargetBranch)

- stage: ExportVariables
  jobs:
  - job: ExportVariables
    steps:
    - template: build/export-variable.yml
      parameters:
        name: 'sourceBranch'
        value: '$(Build.SourceBranch)'
    - template: build/export-variable.yml
      parameters:
        name: 'targetBranch'
        value: '$(System.PullRequest.TargetBranch)'
    - template: build/publish-variables.yml
