# azure-pipelines-ci.yml
#
# Copyright (c) 2020 Radu Traian Jipa
# License: https://opensource.org/licenses/MIT
#
# Continuous integration pipeline for the project.


trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - '*'

steps:
- script: |
    mkdir -p $(Pipeline.Workspace)/pipelineTag/artifactName
    mkdir -p $(Pipeline.Workspace)/anotherPipelineTag/artifactName
    echo "Hello, World!" > $(Pipeline.Workspace)/pipelineTag/artifactName/file.txt
    echo "Look, Mom! No hands!" > $(Pipeline.Workspace)/anotherPipelineTag/artifactName/anotherFile.txt
    ls -l $(Pipeline.Workspace)/*/artifactName
